# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Documents\Data Science\pairwise_gui\ui\tabs\basic_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, basic_info_tab):
        basic_info_tab.setObjectName("basic_info_tab")
        basic_info_tab.resize(1001, 659)
        basic_info_tab.setStyleSheet(
            "*{\n"
            "    background-color: #151515;\n"
            "    color: #fff;\n"
            "    font-family: Lora\n"
            "}\n"
            "\n"
            "#head {\n"
            "    font-size: 10px\n"
            "}"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(basic_info_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QFrame(basic_info_tab)
        self.head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.head.setObjectName("head")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.head)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.head)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.head)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(30, 50, 791, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.head)
        self.main = QtWidgets.QFrame(basic_info_tab)
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.verticalLayout.addWidget(self.main)

        self.retranslateUi(basic_info_tab)
        QtCore.QMetaObject.connectSlotsByName(basic_info_tab)

    def retranslateUi(self, basic_info_tab):
        _translate = QtCore.QCoreApplication.translate
        basic_info_tab.setWindowTitle(_translate("basic_info_tab", "Form"))
        self.label.setText(
            _translate(
                "basic_info_tab", "Retrieving Basic Information About Your Sequence"
            )
        )
        self.textBrowser.setHtml(
            _translate(
                "basic_info_tab",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Lora'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'PMingLiU\';">This section let\'s you gather some information about your sequence. For DNA, you can retrieve the nucleotide frequency, GC content, reverse complement, transcription, and translation. Meanwhile, protein sequence can gather data such as open reading frame.</span></p></body></html>',
            )
        )
